# docker-compose.dev.yml
name: boardbeam
services:
  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
    environment:
      - NODE_ENV=development

  server:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8080:8080"
    volumes:
      - ./apps/server:/app
    environment:
      - NODE_ENV=development
      - PORT=8080

  turn:
    image: instrumentisto/coturn
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
    volumes:
      - ./infra/turn/turnserver.conf:/etc/coturn/turnserver.conf:ro

  updater:
    build:
      context: ./infra/updater
    container_name: updater
    env_file: .env.updater
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/stack
    ports:
      - "8088:8080"
    restart: unless-stopped
